### ISSUE TITLE
Static tracker json output is not "prettier" compliant

### ISSUE THREAD

**Issue by gabe-l-hart** [IBM/import-tracker#11]
## Description

It's missing a newline at the end :gasp:! As a user of `prettier`, I'd like to be able to run my CI without needing to modify the generated file.

## Discussion

Provide detailed discussion here

## Acceptance Criteria

-   [ ] Unit tests cover new/changed code
-   [ ] Examples build against new/changed code
-   [ ] READMEs are updated
-   [ ] Type of [semantic version](https://semver.org/) change is identified
